spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
server:
  port: 8090